# Generated by Django 3.2.3 on 2021-05-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='os',
            field=models.BooleanField(max_length=255, verbose_name='Тип ОС'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera',
            field=models.BooleanField(max_length=255, verbose_name='Качество'),
        ),
    ]
