# Generated by Django 3.2.3 on 2021-05-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_smartphone_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonym_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
